### ISSUE TITLE
Description is lacking.

### ISSUE THREAD

**Issue by jamescurran** [adrian-soomro/jira-commenter#17]
The description is rather vague on what this extension lets you do (and how you use it).

Before I can get the project leader to approve its installation, I need to make a compelling case for it, and so far all I've got is "This extension says it does something with JIRA".

**Comment by adrian-soomro** [comment]
Hi @jamescurran 

Thanks for the feedback. 

I think the crux of the problem lies in that the extension is very simple - all it does is it makes a comment on a JIRA ticket for you (you can achieve the same with a tiny bash script).

`An Azure Devops build extension that will comment on your JIRA tickets for you.` captures that in my opinion and the usage is on the marketplace listing page.

Do you reckon including a link to [the marketplace listing](https://marketplace.visualstudio.com/items?itemName=AdrianSoomro.jira-commenter-task) would make it bit less vague? Or would you propose any better strategy to help with clarity?

**Comment by jamescurran** [comment]
What does the comment it makes say?  IS it autogenerated, or based on something I enter?

**Comment by adrian-soomro** [comment]
I see your point, thanks for letting me know it was vague. I've added some more information in #18 hope it's clearer now.
